#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
echo "-----> Installing libreoffice ..."
COMMAND=$(cat <<EOF
apt-get -y  update 
apt-get install -y default-jre libxinerama1 libdbus-1-dev libcups2-dev libx11-xcb-dev
cd /tmp && wget https://www.libreoffice.org/donate/dl/deb-x86_64/7.3.7/en-US/LibreOffice_7.3.7_Linux_x86-64_deb.tar.gz
cd /tmp && tar zxvf LibreOffice_7.3.7_Linux_x86-64_deb.tar.gz
cd /tmp/LibreOffice_7.3.7.2_Linux_x86-64_deb/DEBS && dpkg -i *.deb
cd /usr/local/bin && ln -s /opt/libreoffice7.3/program/soffice /usr/local/bin/soffice
echo "-----> libreoffice installed!"
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
